### PR TITLE
Refactor the Prop Group implementation and fix RefactoredProp

### LINKED ISSUE #54: RefactoredProp has inconsistent behaviour due to using AbstractPropGroup
# What

Needs further thought, but most likely needs to not use a PropGroup and instead rely on a new construct that has a clear order of precedence.

```
    // TODO(mihaibojin): this is somewhat of a dubious side-effect of using AbstractPropGroup
    //                   as a store for RefactoredProp-s; need to rethink if this makes sense
    //                   (last prop to be updated decides the value and correctness) or if
    //                   given prop2, it should always take precedence regardless of prop1's
    //                   value/error.  On the other hand, maybe the logic should be: try prop2,
    //                   if missing or error, try prop1, and if missing or error, throw 1/2
    //                   exceptions.
```

### PR DESCRIPTION
**Pull request by MihaiBojin**
# Why?
- simpler implementations
- rely on Atomic operations and avoid synchronization

# What?
- complete refactor of `AbstractPropGroup`
- drive-by: register a `Scheduler` and allow using different `ExecutorService` and `ForkJoinPool` implementations
- closes #54 (RefactoredProp now behaves as expected; the refactored prop takes precedence (including any exceptions), or otherwise the original prop is consulted)
- added tests to ensure that an exception is returned by `PropGroup#get()` and that all exceptions are passed down to error subscribers

# Checklist

Please ensure the following conditions are met:

[comment]: <> (- [ ] I have signed the [CLA]&#40;../CLA.md&#41; &#40;additional [details here]&#40;/contributors/README.md&#41;&#41;)

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)

Thank you!

### CODE REVIEW

File: props-core/src/main/java/sh/props/Registry.java [hunk 1]
```diff
@@ -53,10 +52,12 @@
   final List<Layer> layers = new ArrayList<>();
   final ConcurrentHashMap<String, HashSet<AbstractProp<?>>> notifications =
       new ConcurrentHashMap<>();
+  private final Scheduler scheduler;
 
   /** Ensures a registry can only be constructed through a builder. */
-  Registry() {
+  Registry(Scheduler scheduler) {
```
Comment (MihaiBojin) [inline props-core/src/main/java/sh/props/Registry.java:58]: bind a scheduler to the registry, to allow configuring the executor/fork-join pool sizes/strategies.

File: props-core/src/main/java/sh/props/SubscribableProp.java [hunk 2]
```diff
@@ -133,36 +135,36 @@ protected void onValueUpdate(@Nullable T value, long epoch) {
...
-                }
-
-                // send the same value to all consumers
-                this.updateHandlers.forEach(c -> c.accept(value));
-              } finally {
-                // allow the next update to be sent
-                this.sendStage.unlock();
-              }
-            });
+    Scheduler runner = scheduler != null ? scheduler : Scheduler.instance();
```
Comment (MihaiBojin) [inline props-core/src/main/java/sh/props/SubscribableProp.java:138]: Allows offloading async processing to a custom scheduler (provided by the Registry, upon `bind`ing)

File: props-core/src/main/java/sh/props/exceptions/ValueCannotBeSetException.java [hunk 3]
```diff
@@ -25,17 +25,17 @@
...
 
-/**
- * Signals that a Prop object could not be updated to a new value.
- *
- * <p>This class is a checked exception because it needs to be handled by the registry and should
- * not be left to callers.
- */
-public class InvalidUpdateOpException extends Exception {
+/** Signals that a Prop object could not be updated to a new value. */
+public class ValueCannotBeSetException extends RuntimeException {
```
Comment (MihaiBojin) [inline props-core/src/main/java/sh/props/exceptions/ValueCannotBeSetException.java:29]: Better naming / unchecked exception.

File: props-core/src/main/java/sh/props/group/PropGroupQuintuple.java [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+  }
+
+  /**
+   * Returns a key for this object. The key is generated using {@link #multiKey(String, String...)}.
+   *
+   * @return the key that identifies this prop group
+   */
+  @Override
+  public String key() {
+    return key;
```
Comment (MihaiBojin) [inline props-core/src/main/java/sh/props/group/PropGroupQuintuple.java]: move to `AbstractPropGroup`

File: props-core/src/main/java/sh/props/group/PropGroupQuintuple.java [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+    V v3 = readVal(third, errors);
+    W v4 = readVal(fourth, errors);
+    X v5 = readVal(fifth, errors);
+
+    if (errors.isEmpty()) {
+      // if no errors, construct a result
+      holderRef.updateAndGet(holder -> holder.value(Tuple.of(v1, v2, v3, v4, v5)));
+    } else {
+      // otherwise, collect all the logged exceptions
+      var exc = new ValueCannotBeReadException("One or more errors");
```
Comment (MihaiBojin) [inline props-core/src/main/java/sh/props/group/PropGroupQuintuple.java]: simplify block with customer exception inheriting from this type

File: props-core/src/main/java/sh/props/group/TemplatedProp.java [hunk 6]
```diff
@@ -183,7 +183,7 @@ protected String renderTemplate(Quad<T, U, V, W> value) {
    * @return a <code>Prop</code> that returns the rendered template on {@link Prop#get()} and also
    *     supports subscriptions
    */
-  public static <T, U, V, W, X> TemplatedProp<Tuple<T, U, V, W, X>> of(
+  public static <T, U, V, W, X> TemplatedProp<Quintuple<T, U, V, W, X>> of(
```
Comment (MihaiBojin) [inline props-core/src/main/java/sh/props/group/TemplatedProp.java:186]: refactored `tuples` implementation

File: props-core/src/main/java/sh/props/tuples/Pair.java [hunk 7]
```diff
@@ -55,21 +56,35 @@
...
    *
+   * @param pair the original pair that will provide the other values
    * @param value the new value to set
+   * @param <T> the type of the first object
+   * @param <U> the type of the second object
    * @return a new object with the value updated
    */
-  public Pair<T, U> updateSecond(@Nullable U value) {
-    return new Pair<>(this.first, value);
+  public static <T, U> Pair<T, U> updateSecond(@Nullable Pair<T, U> pair, @Nullable U value) {
```
Comment (MihaiBojin) [inline props-core/src/main/java/sh/props/tuples/Pair.java:82]: it's more useful for this method to be a static, since we are not always in a situation where an original tuple object exists.  That way, we can call the static and avoid NPE checks in calling code.

File: props-core/src/main/java/sh/props/tuples/Quintuple.java [hunk 8]
```diff
@@ -0,0 +1,265 @@
...
+/**
+ * Defines a tuple of values.
+ *
+ * @param <T> the type of the first object in the tuple
+ * @param <U> the type of the second object in the tuple
+ * @param <V> the type of the third object in the tuple
+ * @param <W> the type of the fourth object in the tuple
+ * @param <X> the type of the fifth object in the tuple
+ */
+public final class Quintuple<T, U, V, W, X> extends Quad<T, U, V, W> {
```
Comment (MihaiBojin) [inline props-core/src/main/java/sh/props/tuples/Quintuple.java:42]: separated Tuple/Quintuple

File: props-core/src/test/java/sh/props/PropGroupAsyncTest.java [hunk 9]
```diff
@@ -40,15 +40,16 @@
 import sh.props.textfixtures.TestIntProp;
 import sh.props.tuples.Pair;
 import sh.props.tuples.Quad;
+import sh.props.tuples.Quintuple;
 import sh.props.tuples.Triple;
 import sh.props.tuples.Tuple;
 
 @SuppressWarnings({"NullAway", "checkstyle:VariableDeclarationUsageDistance"})
-public class CoordinatedAsyncTest extends AwaitAssertionTest {
+public class PropGroupAsyncTest extends AwaitAssertionTest {
```
Comment (MihaiBojin) [inline props-core/src/test/java/sh/props/PropGroupAsyncTest.java:48]: renamed tests to make their ownership/intent more explicit

File: props-core/src/test/java/sh/props/PropGroupExceptionTest.java [hunk 10]
```diff
@@ -0,0 +1,147 @@
...
+import sh.props.exceptions.ValueCannotBeReadException;
+import sh.props.exceptions.ValueCannotBeSetException;
+import sh.props.group.Group;
+import sh.props.sources.InMemory;
+import sh.props.textfixtures.TestErrorOnGetProp;
+import sh.props.textfixtures.TestErrorOnSetProp;
+import sh.props.tuples.Tuple;
+
+@SuppressWarnings("NullAway")
+public class PropGroupExceptionTest {
```
Comment (MihaiBojin) [inline props-core/src/test/java/sh/props/PropGroupExceptionTest.java:46]: tested expected error states in prop groups

File: props-core/src/test/java/sh/props/RefactoredPropTest.java [hunk 11]
```diff
@@ -107,10 +108,10 @@ void valueIsReturnedFromOldProp() {
 
     assertThat(prop1.get(), equalTo("1"));
     assertThat(prop2.get(), equalTo(null));
-    assertThat(supplier.get(), equalTo(1));
+    assertThat(refactoredProp.get(), equalTo(1));
   }
 
-  @RepeatedTest(value = 10)
```
Comment (MihaiBojin) [inline props-core/src/test/java/sh/props/RefactoredPropTest.java:113]: will revisit repeat test behaviour in #74

File: props-core/src/test/java/sh/props/RefactoredPropTest.java [hunk 12]
```diff
@@ -201,16 +201,44 @@ void exceptionWtf() {
     source.put("key1", "1");
 
     // ASSERT
-    // prop2 fails
-    Assertions.assertThrows(InvalidReadOpException.class, prop2::get);
-    // but the RefactoredProp resolves due to a valid prop1
```
Comment (MihaiBojin) [inline props-core/src/test/java/sh/props/RefactoredPropTest.java:206]: fixed; yay! 🥳

File: props-core/src/testFixtures/java/sh/props/textfixtures/TestErrorOnGetProp.java [hunk 13]
```diff
@@ -27,18 +27,28 @@
...
     super(key, defaultValue, null, false, false);
   }
 
+  /**
+   * Helper method to construct reproducible error messages.
+   *
+   * @param value the value that creates the error
+   * @return the error message
+   */
+  public static String errorMessage(Integer value) {
```
Comment (MihaiBojin) [inline props-core/src/testFixtures/java/sh/props/textfixtures/TestErrorOnGetProp.java:44]: standardize error messages

File: props-core/src/testFixtures/java/sh/props/textfixtures/TestErrorOnSetProp.java [hunk 14]
```diff
@@ -27,18 +27,28 @@
...
     super(key, defaultValue, null, false, false);
   }
 
+  /**
+   * Helper method to construct reproducible error messages.
+   *
+   * @param value the value that creates the error
+   * @return the error message
+   */
+  public static String errorMessage(Integer value) {
```
Comment (MihaiBojin) [inline props-core/src/testFixtures/java/sh/props/textfixtures/TestErrorOnSetProp.java:44]: standardize error messages

**Review by MihaiBojin — COMMENTED** [review]
Code review and explanations.
